In [1]:
import warnings
from causalnex.structure import StructureModel

warnings.filterwarnings("ignore")  # silence warnings

sm = StructureModel()

In [2]:
sm.add_edges_from([
    ('health', 'absences'),
    ('health', 'G1')
])

In [7]:
import pandas as pd

data = pd.read_csv('../data/merged_result.csv')
data.head(10)

,id,order_id,driver_id,driver_action,lat,lng,trip_origin,trip_destination,weekday,trip_start_date,holiday,rain,distance,speed
0,1,392001,243828,accepted,6.602207,3.270465,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
1,2,392001,243588,rejected,6.592097,3.287445,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
2,3,392001,243830,rejected,6.596133,3.281784,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
3,4,392001,243539,rejected,6.596142,3.280526,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
4,5,392001,171653,rejected,6.609232,3.288800,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
5,6,392001,245662,rejected,6.593095,3.287759,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
6,7,392001,171651,rejected,6.613538,3.270779,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
7,8,392001,243906,rejected,6.591838,3.276124,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
8,9,392001,226949,rejected,6.610941,3.276126,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059
9,10,392001,243769,rejected,6.617199,3.271723,"6.6010417,3.2766339","6.4501069,3.3916154",1.0,2021-07-01,0.0,0.0,13.039051,216.316059